### ISSUE TITLE
Examples for username/password authentication?

### ISSUE THREAD

**Issue by karthikeayan** [aws-samples/amazon-msk-client-authentication#2]
Can we have examples for SCRAM-SHA-512 based username/password authentication?

**Comment by liko9** [comment]
Is this helpful?  https://github.com/aws-samples/sasl-scram-secrets-manager-client-for-msk

**Comment by karthikeayan** [comment]
Yes, when I opened this AWS didn't had username/password authentication feature. Thank you!
